
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_HOST_MODULE := nasm
LOCAL_DESCRIPTION := NASM, the Netwide Assembler
LOCAL_CATEGORY_PATH := tools

LOCAL_AUTOTOOLS_VERSION := 2.14
LOCAL_AUTOTOOLS_ARCHIVE := $(LOCAL_HOST_MODULE)-$(LOCAL_AUTOTOOLS_VERSION).tar.gz
LOCAL_AUTOTOOLS_SUBDIR := $(LOCAL_HOST_MODULE)-$(LOCAL_AUTOTOOLS_VERSION)

include $(BUILD_AUTOTOOLS)
